sudo: "required"

language: generic

service:
  - docker

before_install:
  - echo "start creating docker image"
  - docker build -t rojae/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true rojae/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-084402789443" 
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acccess_key: $AWS_SECRET_ACCESS_KEY

after_success:
  - echo "Deploy Success"