version: '2.4'
services:
  frontend:
    image: rojae/docker-react-app
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
  