version: '2.4'
services:
  frontend:
    image: rojae/docker-react-app
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: rojae/docker-nginx
    ports:
      -"80:80"
    mem_limit: 128m
    links:
      - frontend
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: ["npm", "run", "test"]